name: Full-Stack CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # BACKEND SETUP
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Backend Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Backend Tests
        run: |
          cd backend
          pytest tests/

      # FRONTEND SETUP
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      # START BACKEND AND FRONTEND FOR CYPRESS TESTING
      - name: Start Backend
        run: |
          cd backend
          flask run --host=0.0.0.0 --port=5000 &
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
      
      - name: Kill Processes on Port 5173
        run: |
          sudo lsof -t -i:5173 | xargs -r kill -9 || true

      - name: Start Frontend
        run: |
          cd frontend
          npm run dev &
        env:
          VITE_API_URL: http://localhost:5000  # Adjust if needed

      - name: Wait for Services
        run: |
          sleep 10  # Wait for backend/frontend to be ready

      # CYPRESS TESTING
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend
          start: npm run dev
          wait-on: 'http://localhost:3000, http://localhost:5174'
          wait-on-timeout: 120